Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Metrics/LineLength:
  Max: 90

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedStyle: ruby19
